# Kubernetes Manifests para Sustainable Shopping Advisor
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sustainable-advisor
  labels:
    app: sustainable-advisor
    tier: microservice
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sustainable-advisor
  template:
    metadata:
      labels:
        app: sustainable-advisor
        tier: microservice
        version: v1
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: sustainable-advisor
        image: sustainable-advisor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
          name: http
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "5002"
        - name: DEBUG
          value: "false"
        - name: BOUTIQUE_FRONTEND_URL
          value: "http://frontend:80"
        - name: RECOMMENDER_AGENT_URL
          value: "http://recommender-agent:5001"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: sustainable-advisor
  labels:
    app: sustainable-advisor
spec:
  type: ClusterIP
  selector:
    app: sustainable-advisor
  ports:
  - name: http
    port: 80
    targetPort: 5002
    protocol: TCP
---
# Service Monitor para Prometheus (opcional)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sustainable-advisor
  labels:
    app: sustainable-advisor
spec:
  selector:
    matchLabels:
      app: sustainable-advisor
  endpoints:
  - port: http
    path: /health
    interval: 30s
---
# HorizontalPodAutoscaler para escalonamento automático
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sustainable-advisor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sustainable-advisor
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# Network Policy para segurança (opcional)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sustainable-advisor-netpol
spec:
  podSelector:
    matchLabels:
      app: sustainable-advisor
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    - podSelector:
        matchLabels:
          app: loadgenerator
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: frontend
  - to:
    - podSelector:
        matchLabels:
          app: recommender-agent
  - {} # Permitir DNS